### ISSUE TITLE
Infinite loop if error during a plot

### ISSUE THREAD

**Issue by Startouf** [GaretJax/sphinx-autobuild#49]
I am watching a directory containing plot code with the `-z` flag. This directory contains graph python code that I am reading in a documentation file using the `plot` directive.

```
#benchmark/report.rst:309 (imported in my sphinx documentation)
.. plot:: ../../benchmark/pyplots/scalability.py

#benchmark/pyplots/scalability.rb
# -*- coding: UTF-8 -*-
#! /usr/bin/python
raise ValueError('I have Thrown an error here !')
```

There is an infinite loop if those python scripts crash during execution (cf the `raise ValueError code`)

Also for some reason the watch line writes `doc/sphinx/benchmark/pyplots/scalability.py changed`instead of `doc/sphinx/../../benchmark/pyplots/scalability.py changed`

```
+--------- doc/sphinx/benchmark/pyplots/scalability.py changed ------------------
benchmark/report.rst:309: WARNING: Exception occurred in plotting scalability
 from /Users/me/dev/myprog/doc/sphinx/../../benchmark/pyplots/scalability.py:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 6, in <module>
ValueError: I have Thrown an error here !
...
| looking for now-outdated files... none found
| pickling environment... done
| checking consistency... done
| preparing documents... done
| writing output... [ 50%] benchmarking
writing output... [100%] index
| generating indices... genindex
| writing additional pages... search
| copying static files... done
| copying extra files... done
| dumping search index in English (code: en) ... done
| dumping object inventory... done
| build succeeded, 16 warnings.
+--------------------------------------------------------------------------------

+--------- doc/sphinx/benchmark/pyplots/scalability.py changed ------------------
# Same
```

In case my directory structure is not clear

```
-- myproject/
-- -- doc/sphinx/
-- -- -- config.py
-- -- -- index.rst (does an `.. include:: ../../benchmark/report.rst`)
-- -- benchmark/
-- -- -- report.rst (does `.. plot:: ../../benchmark/pyplots/scalability.py`)
-- -- -- pyplots/
-- -- -- -- scalability.py
```
And my run command is from the myproject/ directory 
```
sphinx-autobuild doc/sphinx doc/sphinx/_build/html --open-browser -z benchmark/
```

Mac OS X 10.11.6
Python 2.7.12
Sphinx-autobuild Version: 0.6.0

**Comment by qiuwch** [comment]
I also have this issue. I think it is because when the plot is generated, the output is detected as file changes. So everything is started again.

**Comment by pradyunsg** [comment]
Yup! A file that gets generated like that triggers a loop.

Maybe, we need some sort of loop-detection logic here. Hmm...
