### ISSUE TITLE
sphinx-build dependency missing

### ISSUE THREAD

**Issue by bocekm** [GaretJax/sphinx-autobuild#74]
I've installed sphinx-autobuild through pip on Fedora 29.
After running `sphinx-autobuild -z <codesourcepath> "<docspath>" "<outputpath>"` I'm getting:
```
+--------- manually triggered build ---------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/sphinx-autobuild", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/sphinx_autobuild/__init__.py", line 312, in main
    builder.build()
  File "/usr/lib/python2.7/site-packages/sphinx_autobuild/__init__.py", line 175, in build
    subprocess.Popen(args, stdout=slave)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [Makefile:18: livehtml] Error
```
By further investigation I found out that I'm missing sphinx-build executable. I believe this should be marked as dependency. Or at least improve the error message.

* the `args` contained `['sphinx-build', '-v', '-T', '<valid path>', '<valid path>']`

**Comment by sirex** [comment]
And it would be nice to have a command line flag for manually specifying `sphinx-build` executable location.

**Comment by pradyunsg** [comment]
Hah. That's a good point. :)

And, the related request seems to be for #58.
